import { lesson, module, vocab, readQ } from './lesson-factory.mjs';

function makeA2Lesson(id, title, topic, ruleId, canDo, explanation, vocabulary, readingText) {
  return lesson({
    id,
    title,
    topic,
    objectives: [
      `Use ${title.toLowerCase()} accurately in A2 contexts.`,
      'Understand form, meaning, and typical usage.',
      'Produce short spoken and written examples.',
    ],
    canDo,
    warmUp: {
      title: 'Activate prior knowledge',
      prompt: `Before this lesson, recall what you know about ${title.toLowerCase()}. How is it similar or different from Portuguese?`,
      reflectionQuestions: [`When do native speakers use ${title.toLowerCase()}?`, 'Can you think of one example?'],
    },
    explanation,
    grammar: {
      ruleId,
      title,
      rule: explanation.split('\n').find((l) => l.length > 20) || explanation.slice(0, 200),
      examples: vocabulary.slice(0, 3).map((v) => ({ sentence: v.example, note: v.word })),
      commonMistakes: [
        {
          incorrect: vocabulary[0]?.example?.replace(/\b(went|go|will|have|has|can|should)\b/i, 'WRONG') || 'Incorrect example.',
          correct: vocabulary[0]?.example || 'Correct example.',
          explanation: 'Review the grammar rule for this lesson.',
        },
      ],
      tutorHints: ['At A2, encourage English-only explanations after the first example.'],
    },
    vocabulary,
    examples: [{ context: title, sentences: vocabulary.slice(0, 4).map((v) => v.example) }],
    reading: {
      title: `${title} in Context`,
      text: readingText,
      questions: [
        readQ('r1', 'What is the main topic of the text?', 'short_answer', title.toLowerCase(), 'The text illustrates this lesson topic.'),
        readQ('r2', `What does "${vocabulary[0].word}" mean?`, 'short_answer', vocabulary[0].translation.split('/')[0].trim(), vocabulary[0].translation),
        readQ('r3', 'Is this text appropriate for A2 learners?', 'true_false', true, 'Yes — controlled A2 language.'),
        readQ('r4', 'Which sentence best matches the lesson?', 'multiple_choice', vocabulary[1].example, vocabulary[1].example, {
          options: [vocabulary[1].example, vocabulary[0].example.split(' ').reverse().join(' '), 'No sentence fits.', vocabulary[2]?.example || vocabulary[0].example],
        }),
      ],
    },
    writing: {
      prompt: `Write a short paragraph (5–7 sentences) using ${title.toLowerCase()}. Use at least 3 words from the vocabulary list.`,
      minWords: 50,
      rubricHints: ['Use the target structure at least twice.', 'Check tense and word order.'],
      modelAnswer: vocabulary.slice(0, 4).map((v) => v.example).join(' '),
    },
    tutorHints: [
      `Target structure: ${title}.`,
      'Correct gently and ask the learner to reformulate.',
      'Use English for meta-language when possible at A2.',
    ],
  });
}

const A2_LESSON_DATA = [
  ['a2-m1', 'Past Simple', 'Talk about finished actions and experiences in the past.', [
    ['a2-m1-l1', 'Past Simple — Regular Verbs', 'past_simple_regular', 'a2-past-simple-regular', 'I can talk about finished past actions using regular -ed verbs.', 'Regular past: add -ed (work → worked, play → played). Pronunciation: /t/, /d/, /ɪd/.\n\nI worked yesterday. | She played tennis last week.\n\nTime words: yesterday, last night, ago, in 2020.', [vocab('yesterday', 'ontem', 'adverb', 'I worked yesterday.', []), vocab('last week', 'semana passada', 'phrase', 'We visited Rome last week.', []), vocab('ago', 'atrás', 'adverb', 'Two days ago.', []), vocab('finished', 'terminado', 'adjective', 'The film finished at 10.', []), vocab('walked', 'caminhou', 'verb', 'They walked to school.', []), vocab('cleaned', 'limpou', 'verb', 'I cleaned the kitchen.', []), vocab('watched', 'assistiu', 'verb', 'She watched TV.', []), vocab('studied', 'estudou', 'verb', 'He studied for the test.', [])], 'Last Saturday I cleaned my apartment and watched a film. My friends called me in the evening. We talked for an hour about our trip last year. It was a quiet but nice day.'],
    ['a2-m1-l2', 'Past Simple — Irregular Verbs', 'past_simple_irregular', 'a2-past-simple-irregular', 'I can use common irregular past forms.', 'High-frequency irregulars: go→went, see→saw, have→had, do→did, make→made, come→came, get→got, take→took.\n\nI went to the beach. | She saw her friend.', [vocab('went', 'foi', 'verb', 'We went to the cinema.', []), vocab('saw', 'viu', 'verb', 'I saw Maria at the party.', []), vocab('had', 'teve', 'verb', 'They had a great time.', []), vocab('did', 'fez', 'verb', 'He did his homework.', []), vocab('made', 'fez / criou', 'verb', 'She made a cake.', []), vocab('came', 'veio', 'verb', 'My parents came early.', []), vocab('got', 'pegou / recebeu', 'verb', 'I got a message.', []), vocab('took', 'levou / tomou', 'verb', 'We took the bus.', [])], 'Yesterday I went downtown and saw an old friend. We had coffee and talked. She told me she got a new job. I came home late but I was happy.'],
    ['a2-m1-l3', 'Past Simple — Questions & Negatives', 'past_simple_q_neg', 'a2-past-simple-q-neg', 'I can ask and answer past simple questions and make negatives.', "Did + subject + base verb: Did you go? | She didn't come.\n\nWh- past: Where did you live? | What did he say?\n\nDid is the same for all persons.", [vocab('did', 'auxiliar passado', 'auxiliary', 'Did you enjoy it?', []), vocab("didn't", 'não (passado)', 'auxiliary', "I didn't know.", []), vocab('when', 'quando', 'adverb', 'When did they arrive?', []), vocab('why', 'por que', 'adverb', 'Why did she leave?', []), vocab('enjoy', 'aproveitar / gostar', 'verb', 'Did you enjoy the concert?', []), vocab('arrive', 'chegar', 'verb', 'They arrived late.', []), vocab('leave', 'sair / ir embora', 'verb', 'He left early.', [])], 'Did you finish the report? I didn\'t finish mine because the internet stopped. When did the meeting start? It started at nine. Why did the client leave early?'],
    ['a2-m1-l4', 'Past Time Expressions', 'past_time', 'a2-past-time', 'I can use time expressions with the past simple naturally.', 'Last + period: last month, last year | … ago: three years ago | In + past year: in 2019 | On + past day: on Monday (finished)\n\nNo present perfect yet — focus on finished time.', [vocab('last month', 'mês passado', 'phrase', 'I started gym last month.', []), vocab('last year', 'ano passado', 'phrase', 'They moved last year.', []), vocab('in 2020', 'em 2020', 'phrase', 'In 2020 we stayed home.', []), vocab('once', 'uma vez', 'adverb', 'I met him once.', []), vocab('then', 'então / depois', 'adverb', 'We ate, then we left.', []), vocab('suddenly', 'de repente', 'adverb', 'Suddenly it rained.', [])], 'In 2019 I lived in Lisbon. Last year I moved to Porto. Three months ago I changed jobs. At first it was difficult, but then I adapted.'],
  ]],
  ['a2-m2', 'Future — Will & Going To', 'Discuss plans, predictions, and spontaneous decisions.', [
    ['a2-m2-l1', 'Future with Will', 'future_will', 'a2-future-will', 'I can use will for predictions and instant decisions.', 'Will + base verb for all subjects. Contractions: I\'ll, she\'ll.\n\nPredictions: It will rain. | Spontaneous: I\'ll help you!\n\nNegative: won\'t | Question: Will you…?', [vocab('will', 'verbo futuro', 'modal', 'I will call you.', []), vocab("won't", 'não vai', 'modal', "It won't take long.", []), vocab('probably', 'provavelmente', 'adverb', 'She will probably agree.', []), vocab('maybe', 'talvez', 'adverb', 'Maybe we will travel.', []), vocab('promise', 'prometer', 'verb', 'I promise I will be on time.', []), vocab('predict', 'prever', 'verb', 'Experts predict growth.', [])], 'Look at those clouds — it will rain soon. Don\'t worry, I\'ll lend you my umbrella. I think Brazil will win the match. She probably won\'t arrive before noon.'],
    ['a2-m2-l2', 'Future with Going To', 'future_going_to', 'a2-future-going-to', 'I can use going to for plans and evidence-based predictions.', 'Am/is/are + going to + verb.\n\nPlans: I am going to study medicine. | Evidence: Look — he is going to fall!', [vocab('going to', 'ir (futuro planeado)', 'phrase', 'We are going to move.', []), vocab('plan', 'plano', 'noun', 'What is your plan?', []), vocab('intend', 'pretender', 'verb', 'I intend to apply.', []), vocab('prepare', 'preparar', 'verb', 'She is preparing dinner.', []), vocab('trip', 'viagem', 'noun', 'We are planning a trip.', [])], 'Next year I am going to change jobs. We are going to visit my grandparents in July. Watch out! That box is going to fall. They aren\'t going to finish today.'],
    ['a2-m2-l3', 'Present Continuous for Future', 'present_for_future', 'a2-present-for-future', 'I can use present continuous for fixed future arrangements.', 'Am/is/are + -ing for arranged future: I am meeting John at 6.\n\nOften with time expression: tomorrow, on Friday.', [vocab('meeting', 'reunião / encontro', 'noun', 'I am meeting the team at 3.', []), vocab('flying', 'voando / viajar de avião', 'verb', 'We are flying on Tuesday.', []), vocab('arrangement', 'combinado', 'noun', 'It is a firm arrangement.', []), vocab('calendar', 'calendário', 'noun', 'Check your calendar.', [])], 'I am having dinner with clients tomorrow. She is starting her new role on Monday. We are not working next Friday — it is a holiday.'],
    ['a2-m2-l4', 'Plans vs Predictions', 'plans_vs_predictions', 'a2-plans-predictions', 'I can choose between will, going to, and present continuous.', 'Plan/intention → going to | Arrangement with time → present continuous | Prediction/spontaneous → will', [vocab('decision', 'decisão', 'noun', 'It was a quick decision.', []), vocab('evidence', 'evidência', 'noun', 'There is evidence of rain.', []), vocab('spontaneous', 'espontâneo', 'adjective', 'A spontaneous offer.', []), vocab('fixed', 'fixo / marcado', 'adjective', 'A fixed appointment.', [])], 'A: What are you doing this weekend? B: I am visiting my sister — we booked tickets. A: I think it will be cold. B: In that case, I\'ll take a jacket. I\'m going to buy one anyway.'],
  ]],
  ['a2-m3', 'Comparatives & Superlatives', 'Compare people, places, and things.', [
    ['a2-m3-l1', 'Comparatives', 'comparatives', 'a2-comparatives', 'I can compare two things using comparatives.', 'Short adj: -er (old → older) or more + adj (more expensive). Than: She is taller than me.\n\nIrregular: good → better, bad → worse', [vocab('better', 'melhor', 'adjective', 'This option is better.', []), vocab('worse', 'pior', 'adjective', 'Traffic is worse today.', []), vocab('than', 'do que', 'conjunction', 'Cheaper than yesterday.', []), vocab('cheaper', 'mais barato', 'adjective', 'The blue one is cheaper.', []), vocab('more expensive', 'mais caro', 'phrase', 'Flights are more expensive.', [])], 'My phone is newer than yours, but your camera is better. Living in the centre is more expensive than the suburbs. Today traffic is worse than usual.'],
    ['a2-m3-l2', 'Superlatives', 'superlatives', 'a2-superlatives', 'I can use superlatives to say something is #1 in a group.', 'The + -est (the oldest) or the most + adj (the most interesting).\n\nIrregular: the best, the worst', [vocab('the best', 'o melhor', 'phrase', 'This is the best pizza in town.', []), vocab('the worst', 'o pior', 'phrase', 'The worst film ever.', []), vocab('the most', 'o mais', 'phrase', 'The most popular song.', []), vocab('in the world', 'no mundo', 'phrase', 'Famous in the world.', [])], 'It is the tallest building in the city. She is the most experienced person on the team. That was the worst meal we have had.'],
    ['a2-m3-l3', 'As … As', 'as_as', 'a2-as-as', 'I can use as + adjective + as for equal comparisons.', 'Equal: as tall as | Not equal: not as/so expensive as', [vocab('as', 'tão … como', 'adverb', 'As fast as possible.', []), vocab('same', 'mesmo', 'adjective', 'The same price.', []), vocab('equal', 'igual', 'adjective', 'Equal opportunities.', []), vocab('similar', 'similar', 'adjective', 'Similar results.', [])], 'He is as qualified as his colleague. This hotel is not as cheap as the other one. Your idea is as good as mine.'],
    ['a2-m3-l4', 'Too & Enough', 'too_enough', 'a2-too-enough', 'I can use too and enough with adjectives and nouns.', 'Too + adj = excess (too hot) | Adj + enough (big enough) | Enough + noun (enough time)', [vocab('too', 'demais / muito (excesso)', 'adverb', 'Too late to change.', []), vocab('enough', 'suficiente', 'determiner', 'We have enough chairs.', []), vocab('plenty', 'bastante', 'pronoun', 'Plenty of time.', []), vocab('almost', 'quase', 'adverb', 'Almost enough.', [])], 'The soup is too salty. The room isn\'t big enough for twenty people. Do we have enough money? There is plenty of food — too much, actually.'],
  ]],
  ['a2-m4', 'Quantity & Countability', 'Talk about amounts with much, many, few, little.', [
    ['a2-m4-l1', 'Much & Many', 'much_many', 'a2-much-many', 'I can use much and many in questions, negatives, and affirmatives.', 'Many + plural countables | Much + uncountables (mainly ?/−)\n\nA lot of = both in affirmative', [vocab('much', 'muito (incontável)', 'determiner', 'How much sugar?', []), vocab('many', 'muitos', 'determiner', 'How many tickets?', []), vocab('a lot of', 'muito / muitos', 'phrase', 'A lot of traffic.', []), vocab('how much', 'quanto', 'phrase', 'How much does it cost?', [])], 'How many emails did you get today? Too many! There isn\'t much time left. We have a lot of work this week.'],
    ['a2-m4-l2', 'Few & Little', 'few_little', 'a2-few-little', 'I can use few/little/a few/a little correctly.', 'Few/a few + plural | Little/a little + uncountable\n\nFew/little = not enough (negative feel) | A few/a little = some (positive)', [vocab('few', 'poucos', 'determiner', 'Few people came.', []), vocab('little', 'pouco', 'determiner', 'Little progress was made.', []), vocab('a few', 'alguns', 'phrase', 'I have a few questions.', []), vocab('a little', 'um pouco de', 'phrase', 'A little help please.', [])], 'Few customers visited the shop yesterday. We have a little milk — enough for coffee. She speaks a few words of Japanese. There is little hope without a plan.'],
    ['a2-m4-l3', 'Containers & Measures', 'containers', 'a2-containers', 'I can use container words: a bottle of, a cup of, a kilo of.', 'A bottle of water | A cup of tea | A piece of cake | A kilo of rice', [vocab('bottle', 'garrafa', 'noun', 'A bottle of water.', []), vocab('cup', 'xícara', 'noun', 'A cup of coffee.', []), vocab('piece', 'pedaço / fatia', 'noun', 'A piece of bread.', []), vocab('kilo', 'quilo', 'noun', 'Two kilos of apples.', []), vocab('packet', 'pacote', 'noun', 'A packet of biscuits.', [])], 'Can you buy a bottle of juice and two packets of rice? I ate a piece of cake and drank a cup of tea. We need a kilo of tomatoes.'],
    ['a2-m4-l4', 'Countable vs Uncountable', 'countability', 'a2-countability', 'I can classify nouns and choose correct quantifiers.', 'Countable: one apple, two apples | Uncountable: rice, information (no plural *informations)\n\nSome/any/a lot of work with both; much/many depend on type', [vocab('information', 'informação', 'noun', 'Useful information.', []), vocab('advice', 'conselho', 'noun', 'Good advice.', []), vocab('furniture', 'mobília', 'noun', 'Modern furniture.', []), vocab('news', 'notícia(s)', 'noun', 'Good news!', []), vocab('bread', 'pão', 'noun', 'Fresh bread.', [])], 'Can I give you some advice? The furniture is new. There isn\'t much information on the website. These chairs are comfortable — we need many chairs for the event.'],
  ]],
  ['a2-m5', 'Frequency & Modals', 'Express habits, obligation, advice, and preferences.', [
    ['a2-m5-l1', 'Adverbs of Frequency (Review+)', 'frequency_a2', 'a2-frequency', 'I can use frequency adverbs naturally in A2 discourse.', 'Always, usually, often, sometimes, rarely, never — position with one/two verbs.\n\nQuestions: How often do you…?', [vocab('rarely', 'raramente', 'adverb', 'I rarely eat fast food.', []), vocab('every day', 'todos os dias', 'phrase', 'She walks every day.', []), vocab('once a month', 'uma vez por mês', 'phrase', 'I travel once a month.', []), vocab('hardly ever', 'quase nunca', 'phrase', 'He hardly ever complains.', [])], 'I usually wake up early, but I rarely have time for breakfast. How often do you exercise? — About three times a week.'],
    ['a2-m5-l2', 'Should / Shouldn\'t', 'should', 'a2-should', 'I can give advice with should and shouldn\'t.', 'Should + base verb: You should rest. | Shouldn\'t: You shouldn\'t drive tired.\n\nAdvice, recommendation — not strong obligation.', [vocab('should', 'deveria', 'modal', 'You should see a doctor.', []), vocab("shouldn't", 'não deveria', 'modal', "You shouldn't skip meals.", []), vocab('advice', 'conselho', 'noun', 'Take my advice.', []), vocab('recommend', 'recomendar', 'verb', 'I recommend this book.', [])], 'You look ill — you should go home. You shouldn\'t drink coffee at night. What should I wear to the interview?'],
    ['a2-m5-l3', 'Must / Have To', 'must_have_to', 'a2-must-have-to', 'I can express obligation with must and have to.', 'Must = speaker obligation/rules | Have to = external rules\n\nMustn\'t = prohibition | Don\'t have to = no obligation', [vocab('must', 'dever (obrigação)', 'modal', 'You must wear a seatbelt.', []), vocab('have to', 'ter que', 'phrase', 'I have to finish today.', []), vocab("mustn't", 'proibido', 'modal', "You mustn't smoke here.", []), vocab("don't have to", 'não precisa', 'phrase', "You don't have to pay.", [])], 'Employees must badge in. I have to catch the 7 a.m. train. You don\'t have to bring food — lunch is included. You mustn\'t use your phone in the exam.'],
    ['a2-m5-l4', 'Would Like', 'would_like', 'a2-would-like', 'I can make polite offers and requests with would like.', 'Would like + noun / to + verb: I\'d like a tea. | Would you like…?\n\nPoliter than want in service contexts', [vocab('would like', 'gostaria', 'phrase', 'I would like the bill.', []), vocab('order', 'pedir / pedido', 'verb', 'Are you ready to order?', []), vocab('prefer', 'preferir', 'verb', 'I prefer tea.', []), vocab('something', 'algo', 'pronoun', 'Something to drink?', [])], 'Would you like a table by the window? I\'d like to book a room for two nights. She would like something vegetarian.'],
  ]],
  ['a2-m6', 'Present Perfect Intro', 'Link past actions to the present.', [
    ['a2-m6-l1', 'Present Perfect Form', 'present_perfect_form', 'a2-present-perfect', 'I can form present perfect with have/has + past participle.', 'Have/has + past participle: I have finished. | She has lived here for years.\n\nPast participle: regular -ed, irregular tables', [vocab('have been', 'esteve / esteve em', 'phrase', 'I have been to Chile.', []), vocab('has done', 'fez', 'phrase', 'She has done the work.', []), vocab('past participle', 'particípio passado', 'noun', 'Learn the past participle.', []), vocab('experience', 'experiência', 'noun', 'An interesting experience.', []), vocab('already', 'já', 'adverb', 'I have already eaten.', [])], 'I have worked here since 2022. She has never tried sushi. We have just arrived — sorry we\'re late.'],
    ['a2-m6-l2', 'Ever & Never', 'ever_never', 'a2-ever-never', 'I can ask about life experiences with ever and never.', 'Have you ever…? | I have never…\n\nEver in questions; never in negatives (no double negative)', [vocab('ever', 'alguma vez', 'adverb', 'Have you ever been abroad?', []), vocab('never', 'nunca', 'adverb', 'I have never flown.', []), vocab('before', 'antes', 'adverb', 'Not like this before.', []), vocab('yet', 'ainda (?)', 'adverb', 'Have you finished yet?', [])], 'Have you ever ridden a horse? — No, never. Has she ever lived abroad? — Yes, she lived in Spain once.'],
    ['a2-m6-l3', 'For & Since', 'for_since', 'a2-for-since', 'I can use for and since with present perfect duration.', 'Since + point (since 2020, since Monday) | For + period (for three years)\n\nPresent perfect with unfinished time', [vocab('since', 'desde', 'preposition', 'Since last year.', []), vocab('for', 'por / durante', 'preposition', 'For two hours.', []), vocab('how long', 'há quanto tempo', 'phrase', 'How long have you known her?', []), vocab('duration', 'duração', 'noun', 'The duration of the contract.', [])], 'I have known him since university. She has worked here for six months. How long have you had this car? — For about five years.'],
    ['a2-m6-l4', 'Just, Already & Yet', 'just_already_yet', 'a2-just-already-yet', 'I can use just, already, and yet in present perfect contexts.', 'Just = very recent | Already = before expected | Yet = until now (?/−)', [vocab('just', 'acabar de', 'adverb', 'I have just sent the email.', []), vocab('already', 'já', 'adverb', 'They have already left.', []), vocab('yet', 'ainda', 'adverb', 'Have you replied yet?', []), vocab('recent', 'recente', 'adjective', 'Recent changes.', [])], 'I have just finished the report. She has already told the manager. We haven\'t decided yet. Have they arrived yet? — Yes, they have just arrived.'],
  ]],
  ['a2-m7', 'First Conditional', 'Talk about real future possibilities.', [
    ['a2-m7-l1', 'If + Present, Will', 'first_conditional', 'a2-first-conditional', 'I can use the first conditional for real future possibilities.', 'If + present simple, will + base: If it rains, I will stay home.\n\nOrder can change: I will call if I am late.', [vocab('if', 'se', 'conjunction', 'If you need help, call me.', []), vocab('unless', 'a menos que', 'conjunction', 'Unless it rains, we will go.', []), vocab('probably', 'provavelmente', 'adverb', 'It will probably work.', []), vocab('condition', 'condição', 'noun', 'On one condition.', [])], 'If the client agrees, we will sign tomorrow. You will miss the train if you don\'t hurry. If I have time, I\'ll join the meeting.'],
    ['a2-m7-l2', 'Unless & As Long As', 'unless', 'a2-unless', 'I can use unless and as long as in conditional sentences.', 'Unless = if not | As long as = provided that\n\nSame tense pattern as first conditional', [vocab('as long as', 'contanto que', 'phrase', 'As long as you try.', []), vocab('provided', 'desde que', 'conjunction', 'Provided you pay on time.', []), vocab('otherwise', 'caso contrário', 'adverb', 'Hurry, otherwise you will be late.', [])], 'Unless the weather improves, we will cancel the picnic. You can borrow it as long as you return it. I won\'t go unless you come with me.'],
    ['a2-m7-l3', 'Real Conditions in Context', 'conditional_context', 'a2-conditional-context', 'I can use first conditional in emails, negotiations, and plans.', 'Professional: If we receive payment, we will ship Monday.\n\nMix with when for scheduled conditions.', [vocab('receive', 'receber', 'verb', 'When we receive approval…', []), vocab('approve', 'aprovar', 'verb', 'If they approve the budget…', []), vocab('negotiate', 'negociar', 'verb', 'We can negotiate if…', []), vocab('deadline', 'prazo', 'noun', 'Meet the deadline.', [])], 'If we receive the signed contract today, we will start onboarding tomorrow. When the payment clears, you will get access. If costs rise, we will need to renegotiate.'],
    ['a2-m7-l4', 'Mixed Conditionals Intro', 'mixed_cond_intro', 'a2-mixed-cond-intro', 'I can recognize when a condition refers to present/future result (A2 preview).', 'Focus on first conditional; brief contrast: unreal conditions use past (If I had… — B1 preview).\n\nDon\'t over-teach — awareness only.', [vocab('real', 'real', 'adjective', 'A real possibility.', []), vocab('unreal', 'irreal', 'adjective', 'An unreal dream.', []), vocab('likely', 'provável', 'adjective', 'A likely outcome.', []), vocab('unlikely', 'improvável', 'adjective', 'An unlikely event.', [])], 'If I study every day, I will improve — real and likely. (Preview: If I were rich, I would travel — not A2 productive yet.) Choose first conditional for realistic plans.'],
  ]],
  ['a2-m8', 'Lexis & Phrasal Verbs', 'Expand vocabulary with common phrasal verbs and collocations.', [
    ['a2-m8-l1', 'Common Phrasal Verbs 1', 'phrasals_1', 'a2-phrasals-1', 'I can understand and use get up, turn on, look for, pick up.', 'Separable/inseparable basics: turn on the light / turn the light on\n\nGet up, wake up, go out, come back', [vocab('get up', 'levantar-se', 'phrasal verb', 'I get up at six.', []), vocab('turn on', 'ligar', 'phrasal verb', 'Turn on the TV.', []), vocab('look for', 'procurar', 'phrasal verb', 'I am looking for my keys.', []), vocab('pick up', 'buscar / pegar', 'phrasal verb', 'Pick up the children at 3.', []), vocab('go out', 'sair', 'phrasal verb', 'We go out on Fridays.', [])], 'I get up early and look for my shoes. Turn on the heater — it is cold. Can you pick up milk on your way home?'],
    ['a2-m8-l2', 'Common Phrasal Verbs 2', 'phrasals_2', 'a2-phrasals-2', 'I can use take off, put on, run out of, find out.', 'Take off (clothes/plane) | Put on | Run out of | Find out\n\nContext helps meaning.', [vocab('take off', 'tirar / decolar', 'phrasal verb', 'The plane takes off at noon.', []), vocab('put on', 'vestir / colocar', 'phrasal verb', 'Put on your jacket.', []), vocab('run out of', 'ficar sem', 'phrasal verb', 'We ran out of milk.', []), vocab('find out', 'descobrir', 'phrasal verb', 'I found out the truth.', [])], 'We ran out of paper. I need to find out the price. Put on sunscreen — it is sunny. The flight takes off in ten minutes.'],
    ['a2-m8-l3', 'Collocations', 'collocations', 'a2-collocations', 'I can use natural word pairs: make a mistake, do homework, heavy rain.', 'Make vs do: make a decision, do your best\n\nStrong tea, heavy traffic, fast food', [vocab('make a mistake', 'cometer um erro', 'phrase', 'Everyone makes mistakes.', []), vocab('do homework', 'fazer lição de casa', 'phrase', 'I do homework after dinner.', []), vocab('heavy rain', 'chuva forte', 'phrase', 'Heavy rain expected.', []), vocab('fast food', 'comida rápida', 'phrase', 'Avoid too much fast food.', []), vocab('strong coffee', 'café forte', 'phrase', 'I prefer strong coffee.', [])], 'I made a mistake on the form. She did her best in the interview. There was heavy rain and traffic was terrible.'],
    ['a2-m8-l4', 'Review & Useful Idioms', 'idioms_review', 'a2-idioms', 'I can understand basic idioms and review A2 lexis.', 'Break the ice, piece of cake, under the weather (intro level)\n\nReview phrasals and collocations from the module', [vocab('break the ice', 'quebrar o gelo', 'idiom', 'A joke breaks the ice.', []), vocab('piece of cake', 'muito fácil', 'idiom', 'The test was a piece of cake.', []), vocab('under the weather', 'indisposto', 'idiom', 'I feel under the weather.', []), vocab('review', 'revisar', 'verb', 'Let us review the vocabulary.', [])], 'At the start of the meeting, a short game broke the ice. The setup was a piece of cake. Two colleagues were under the weather and joined online. Time to review before the module test.'],
  ]],
];

export const A2_MODULES = A2_LESSON_DATA.map(([modId, modTitle, modDesc, lessons], mi) =>
  module(modId, 'a2', mi + 1, modTitle, modDesc, `I can use ${modTitle.toLowerCase()} confidently at A2 level.`, lessons.map(([id, title, topic, ruleId, canDo, explanation, vocabulary, readingText], li) =>
    makeA2Lesson(id, title, topic, ruleId, canDo, explanation, vocabulary, readingText)
  ))
);
